---
## Section 1 ##
SEC_ID_FILESYSTEM_CONFIGURATIONS: "1.1"
SEC_ID_DISABLE_UNUSED_FILESYSTEMS: "1.1.1"
SEC_ID_CONFIGURE_TMP: "1.1.2"
SEC_ID_CONFIGURE_TMP_NODEV: "1.1.3"
SEC_ID_CONFIGURE_TMP_NOSUID: "1.1.4"
SEC_ID_CONFIGURE_TMP_NOEXEC: "1.1.5"
SEC_ID_CONFIGURE_SHM: "1.1.6"
SEC_ID_CONFIGURE_SHM_NODEV: "1.1.7"
SEC_ID_CONFIGURE_SHM_NOSUID: "1.1.8"
SEC_ID_CONFIGURE_SHM_NOEXEC: "1.1.9"
SEC_ID_SEPARATE_VAR: "1.1.10"
SEC_ID_SEPARATE_VAR_TMP: "1.1.11"
SEC_ID_CONFIGURE_VAR_TMP_NODEV: "1.1.12"
SEC_ID_CONFIGURE_VAR_TMP_NOSUID: "1.1.13"
SEC_ID_CONFIGURE_VAR_TMP_NOEXEC: "1.1.14"
SEC_ID_SEPARATE_VAR_LOG: "1.1.15"
SEC_ID_SEPARATE_VAR_LOG_AUDIT: "1.1.16"
SEC_ID_SEPARATE_HOME: "1.1.17"
SEC_ID_CONFIGURE_HOME_NODEV: "1.1.18"
SEC_ID_CONFIGURE_MEDIA_NODEV: "1.1.19"
SEC_ID_CONFIGURE_MEDIA_NOSUID: "1.1.20"
SEC_ID_CONFIGURE_MEDIA_NOEXEC: "1.1.21"
SEC_ID_WORLD_WRITABLE_STICKY_BIT: "1.1.22"
SEC_ID_DISABLE_AUTOMOUNT: "1.1.23"
SEC_ID_DISABLE_USB_STORAGE: "1.1.24"

SEC_ID_CONFIGURE_SOFTWARE_UPDATES: "1.2"
SEC_ID_CONFIGURE_GPG_KEYS: "1.2.1"
SEC_ID_CONFIGURE_PACKAGE_MANAGER_REPOS: "1.2.2"
SEC_ID_ACTIVATE_GPG_GLOBALLY: "1.2.3"
SEC_ID_CONFIGURE_RHSM: "1.2.4"
SEC_ID_DISABLE_RHNSD: "1.2.5"

SEC_ID_CONFIGURE_SUDO: "1.3"
SEC_ID_ENSURE_SUDO_INSTALLED: "1.3.1"
SEC_ID_ENSURE_SUDO_PTY: "1.3.2"
SEC_ID_ENSURE_SUDO_LOG_EXISTS: "1.3.3"

SEC_ID_CONFIGURE_FILESYSTEM_INTEGRITY: "1.4"
SEC_ID_AIDE_SETUP: "1.4.1"
SEC_ID_AIDE_SCHEDULE: "1.4.2"

SEC_ID_SECURE_BOOT_SETTINGS: "1.5"
SEC_ID_BOOT_PASSWORD: "1.5.1"
SEC_ID_BOOTLOADER_PERMS: "1.5.2"
SEC_ID_SINGLE_USER_AUTH_NEEDED: "1.5.3"

SEC_ID_ADDITIONAL_PROCESS_HARDENING: "1.6"
SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED: "1.6.1"
SEC_ID_ENSURE_NX_ND_SUPPORT_ENABLED: "1.6.2"
SEC_ID_ENSURE_ADDRESS_SPACE_RANDOMIZATION_ENABLED: "1.6.3"
SEC_ID_ENSURE_PRELINK_NOT_INSTALLED: "1.6.4"

SEC_ID_MANDATORY_ACCESS_CONTROL: "1.7"
SEC_ID_ENSURE_SELINUX_INSTALLED: "1.7.1.1"
SEC_ID_ENSURE_SELINUX_NOT_DISABLED_IN_BOOTLOADER: "1.7.1.2"
SEC_ID_ENSURE_SELINUX_POLICY_CONFIGURED: "1.7.1.3"
SEC_ID_ENSURE_SELINUX_MODE_ENFORCING_OR_PERMISSIVE: "1.7.1.4"
SEC_ID_ENSURE_SELINUX_MODE_ENFORCING: "1.7.1.5"
SEC_ID_ENSURE_NO_UNCONFINED_SERVICES_EXIST: "1.7.1.6"
SEC_ID_ENSURE_SETROUBLESHOOT_NOT_INSTALLED: "1.7.1.7"
SEC_ID_ENSURE_MCSTRANS_NOT_INSTALLED: "1.7.1.8"

SEC_ID_COMMAND_LINE_WARNING_BANNERS: "1.8"
SEC_ID_ENSURE_MOTD_CONFIGURED: "1.8.1"
SEC_ID_ENSURE_LOCAL_LOGIN_BANNER_CONFIGURED: "1.8.2"
SEC_ID_ENSURE_REMOTE_LOGIN_BANNER_CONFIGURED: "1.8.3"
SEC_ID_ENSURE_ETC_MOTD_PERMISSIONS_CONFIGURED: "1.8.4"
SEC_ID_ENSURE_ETC_ISSUE_PERMISSIONS_CONFIGURED: "1.8.5"
SEC_ID_ENSURE_ETC_ISSUE_NET_PERMISSIONS_CONFIGURED: "1.8.6"

SEC_ID_UPDATES_AND_PATCHES: "1.9"
SEC_ID_ENSURE_UPDATES_AND_PATCHES_INSTALLED: "1.9.1"

## Section 2 ##
SEC_ID_INETD_SERVICES: "2.1"
SEC_ID_ENSURE_XINETD_NOT_INSTALLED: "2.1.1"

SEC_ID_SPECIAL_PURPOSE_SERVICES: "2.2"
SEC_ID_TIME_SYNCHRONIZATION: "2.2.1"
SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE: "2.2.1.1"
SEC_ID_ENSURE_CHRONY_CONFIGURED: "2.2.1.2"
SEC_ID_ENSURE_NTPD_CONFIGURED: "2.2.1.3"
SEC_ID_X11_COMPONENTS_NOT_INSTALLED: "2.2.2"
SEC_ID_AVAHI_SERVER_NOT_INSTALLED: "2.2.3"
SEC_ID_CUPS_SERVER_NOT_INSTALLED: "2.2.4"
SEC_ID_DHCP_SERVER_NOT_INSTALLED: "2.2.5"
SEC_ID_LDAP_SERVER_NOT_INSTALLED: "2.2.6"
SEC_ID_DNS_SERVER_NOT_INSTALLED: "2.2.7"
SEC_ID_FTP_SERVER_NOT_INSTALLED: "2.2.8"
SEC_ID_HTTP_SERVER_NOT_INSTALLED: "2.2.9"
SEC_ID_IMAP_POP3_SERVER_NOT_INSTALLED: "2.2.10"
SEC_ID_SAMBA_SERVER_NOT_INSTALLED: "2.2.11"
SEC_ID_HTTP_PROXY_SERVER_NOT_INSTALLED: "2.2.12"
SEC_ID_NET_SNMP_NOT_INSTALLED: "2.2.13"
SEC_ID_NIS_SERVER_NOT_INSTALLED: "2.2.14"
SEC_ID_TELNET_SERVER_NOT_INSTALLED: "2.2.15"
SEC_ID_MTA_CONFIGURED_LOCAL_ONLY: "2.2.16"
SEC_ID_NFS_UTILS_NOT_INSTALLED: "2.2.17"
SEC_ID_RPC_BIND_NOT_INSTALLED: "2.2.18"
SEC_ID_RSYNC_NOT_INSTALLED: "2.2.19"

SEC_ID_SERVICE_CLIENTS: "2.3"
SEC_ID_ENSURE_NIS_CLIENT_NOT_INSTALLED: "2.3.1"
SEC_ID_ENSURE_RSH_CLIENT_NOT_INSTALLED: "2.3.2"
SEC_ID_ENSURE_TALK_CLIENT_NOT_INSTALLED: "2.3.3"
SEC_ID_ENSURE_TELNET_CLIENT_NOT_INSTALLED: "2.3.4"
SEC_ID_ENSURE_LDAP_CLIENT_NOT_INSTALLED: "2.3.5"

SEC_ID_NON_ESSENTIAL_SERVICES: "2.4"

## Section 3 ##
SEC_ID_DISABLE_UNUSED_PROTOCOLS_DEVICES: "3.1"
SEC_ID_DISABLE_IPV6: "3.1.1"
SEC_ID_ENSURE_WIRELESS_INTERFACE_DISABLED: "3.1.2"

SEC_ID_NETWORK_PARAMETERS_HOST_ONLY: "3.2"
SEC_ID_ENSURE_IP_FORWARDING_DISABLED: "3.2.1"
SEC_ID_ENSURE_PACKET_REDIRECT_DISABLED: "3.2.2"

SEC_ID_NETWORK_PARAMETERS_HOST_ROUTER: "3.3"
SEC_ID_ENSURE_SOURCE_ROUTED_PACKETS_NOT_ACCEPTED: "3.3.1"
SEC_ID_ENSURE_ICMP_REDIRECTS_NOT_ACCEPTED: "3.3.2"
SEC_ID_ENSURE_SECURE_ICMP_REDIRECTS_NOT_ACCEPTED: "3.3.3"
SEC_ID_ENSURE_SUSPICIOUS_PACKETS_LOGGED: "3.3.4"
SEC_ID_ENSURE_BROADCAST_ICMP_REQUESTS_IGNORED: "3.3.5"
SEC_ID_ENSURE_BOGUS_ICMP_RESPONSES_IGNORED: "3.3.6"
SEC_ID_ENSURE_REVERSE_PATH_FILTERING_ENABLED: "3.3.7"
SEC_ID_ENSURE_TCP_SYN_COOKIES_ENABLED: "3.3.8"
SEC_ID_ENSURE_ROUTER_ADVERTISEMENTS_NOT_ACCEPTED: "3.3.9"

SEC_ID_NETWORK_UNCOMMON_NETWORK_PROTOCOLS: "3.4"
SEC_ID_ENSURE_DCCP_DISABLED: "3.4.1"
SEC_ID_ENSURE_SCTP_DISABLED: "3.4.2"

SEC_ID_FIREWALL_CONFIGURATION: "3.5"
SEC_ID_CONFIGURE_FIREWALLD: "3.5.1"
SEC_ID_ENSURE_FIREWALLD_INSTALLED: "3.5.1.1"
SEC_ID_ENSURE_IPTABLES_NOT_INSTALLED_WITH_FIREWALLD: "3.5.1.2"
SEC_ID_ENSURE_NFTABLES_DISABLED_WITH_FIREWALLD: "3.5.1.3"
SEC_ID_ENSURE_FIREWALLD_SERVICE_ENABLED: "3.5.1.4"
SEC_ID_ENSURE_FIREWALLD_DEFAULT_ZONE_NOT_SET: "3.5.1.5"
SEC_ID_ENSURE_NETWORK_INTERFACES_ASSIGNED_TO_APPROPRIATE_USE: "3.5.1.6"
SEC_ID_ENSURE_FIREWALLD_DROPS_UNNECESSARY_SERVICES_PORTS: "3.5.1.7"
SEC_ID_ENSURE_NFTABLES_INSTALLED: "3.5.2.1"
SEC_ID_ENSURE_FIREWALLD_NOT_INSTALLED_WITH_NFTABLES: "3.5.2.2"
SEC_ID_ENSURE_IPTABLES_NOT_INSTALLED_WITH_NFTABLES: "3.5.2.3"
SEC_ID_ENSURE_IPTABLES_ARE_FLUSHED_WITH_NFTABLES: "3.5.2.4"
SEC_ID_ENSURE_AN_NFTABLES_TABLE_EXISTS: "3.5.2.5"
SEC_ID_ENSURE_NFTABLES_BASE_CHAINS_EXISTS: "3.5.2.6"
SEC_ID_ENSURE_NFTABLES_LOOPBACK_TRAFFIC_CONFIGURED: "3.5.2.7"
SEC_ID_ENSURE_NFTABLES_OUTBOUND_AND_ESTABILISHED_CONNECTION_CONFIGURED: "3.5.2.8"
SEC_ID_ENSURE_NFTABLES_DEFAULT_DENY_FIREWALL_POLICY: "3.5.2.9"
SEC_ID_ENSURE_NFTABLES_SERVICE_ENABLED: "3.5.2.10"
SEC_ID_ENSURE_NFTABLES_RULES_PERMANENT: "3.5.2.11"
SEC_ID_ENSURE_IPTABLES_INSTALLED: "3.5.2.1.1"
SEC_ID_ENSURE_NFTABLES_NOT_INSTALLED_WITH_IPTABLES: "3.5.2.1.2"
SEC_ID_ENSURE_FIREWALLD_NOT_INSTALLED_WITH_IPTABLES: "3.5.2.1.3"

## Section 4 ##
SEC_ID_CONFIGURE_SYSTEM_ACCOUNTING: "4.1"

SEC_ID_ENSURE_AUDITING_ENABLED: "4.1.1"
SEC_ID_ENSURE_AUDITD_INSTALLED: "4.1.1.1"
SEC_ID_ENSURE_AUDITD_ENABLED: "4.1.1.2"
SEC_ID_ENSURE_AUDITING_FOR_PRE_AUDITD_SERVICES_ENABLED: "4.1.1.3"

SEC_ID_CONFIGURE_DATA_RETENTION: "4.1.2"
SEC_ID_ENSURE_AUDIT_LOG_STORAGE_ENABLED: "4.1.2.1"
SEC_ID_ENSURE_AUDIT_LOGS_NOT_AUTOMATICALLY_DELETED: "4.1.2.2"
SEC_ID_ENSURE_SYSTEM_DISABLED_WHEN_AUDIT_FULL: "4.1.2.3"
SEC_ID_ENSURE_AUDIT_BACKLOG_LIMIT_SUFFICIENT: "4.1.2.4"

SEC_ID_ENSURE_DATE_TIME_EVENTS_COLLECTED: "4.1.3"
SEC_ID_ENSURE_USER_GROUP_EVENTS_COLLECTED: "4.1.4"
SEC_ID_ENSURE_NETWORK_ENVIRONMENT_EVENTS_COLLECTED: "4.1.5"
SEC_ID_ENSURE_MANDATORY_ACCESS_CONTROL_EVENTS_COLLECTED: "4.1.6"
SEC_ID_ENSURE_LOGIN_LOGOUT_EVENTS_COLLECTED: "4.1.7"
SEC_ID_ENSURE_SESSION_INIT_INFO_COLLECTED: "4.1.8"
SEC_ID_ENSURE_DISC_ACC_CTRL_PERM_COLLECTED: "4.1.9"
SEC_ID_ENSURE_UNAUTH_FILE_ACCESS_COLLECTED: "4.1.10"
SEC_ID_ENSURE_PRIV_COMMANDS_COLLECTED: "4.1.11"
SEC_ID_ENSURE_FS_MOUNTS_COLLECTED: "4.1.12"
SEC_ID_ENSURE_FILE_DELETION_EVENTS_COLLECTED: "4.1.13"
SEC_ID_ENSURE_SUDOERS_CHANGES_COLLECTED: "4.1.14"
SEC_ID_ENSURE_SUDO_COMMANDS_COLLECTED: "4.1.15"
SEC_ID_ENSURE_KERNEL_MODULE_ACTIONS_COLLECTED: "4.1.16"
SEC_ID_ENSURE_AUDIT_CONFIG_IMMUTABLE: "4.1.17"

SEC_ID_CONFIGURE_LOGGING: "4.2"

SEC_ID_CONFIGURE_RSYSLOG: "4.2.1"
SEC_ID_ENSURE_RSYSLOG_INSTALLED: "4.2.1.1"
SEC_ID_ENSURE_RSYSLOG_ENABLED: "4.2.1.2"
SEC_ID_ENSURE_DEFAULT_FILE_PERMS: "4.2.1.3"
SEC_ID_ENSURE_LOGGING_CONFIGURED: "4.2.1.4"
SEC_ID_ENSURE_RSYSLOG_REMOTE_LOGGING: "4.2.1.5"
SEC_ID_ENSURE_RSYSLOG_ONLY_REMOTE_ACCEPTED: "4.2.1.6"

SEC_ID_CONFIGURE_JOURNALD: "4.2.2"
SEC_ID_ENSURE_JOURNALD_TO_RSYSLOG: "4.2.2.1"
SEC_ID_ENSURE_JOURNALD_COMPRESSION: "4.2.2.2"
SEC_ID_ENSURE_WRITE_TO_PERSISTENT_DISK: "4.2.2.3"

SEC_ID_ENSURE_LOGFILE_PERMISSIONS: "4.2.3"
SEC_ID_ENSURE_LOGROTATE_CONFIGURED: "4.2.4"


## Section 5 ##
SEC_ID_CONFIGURE_CRON: "5.1"
SEC_ID_ENSURE_CRON_ENABLED: "5.1.1"
SEC_ID_ENSURE_CRONTAB_PERMISSIONS: "5.1.2"
SEC_ID_ENSURE_CRON_HOURLY_PERMISSIONS: "5.1.3"
SEC_ID_ENSURE_CRON_DAILY_PERMISSIONS: "5.1.4"
SEC_ID_ENSURE_CRON_WEEKLY_PERMISSIONS: "5.1.5"
SEC_ID_ENSURE_CRON_MONTHLY_PERMISSIONS: "5.1.6"
SEC_ID_ENSURE_CRON_D_PERMISSIONS: "5.1.7"
SEC_ID_ENSURE_CRON_RESTRICTED: "5.1.8"
SEC_ID_ENSURE_AT_RESTRICTED: "5.1.9"

SEC_ID_CONFIGURE_SSH: "5.2"
SEC_ID_ENSURE_SSHD_PERMISSIONS: "5.2.1"
SEC_ID_ENSURE_SSH_PRIVATE_HOST_KEY_FILES: "5.2.2"
SEC_ID_ENSURE_SSH_PUBLIC_HOST_KEY_FILES: "5.2.3"
SEC_ID_ENSURE_SSH_ACCESS_LIMITED: "5.2.4"
SEC_ID_ENSURE_SSH_LOGLEVEL: "5.2.5"
SEC_ID_ENSURE_SSH_X11_FW_DISABLED: "5.2.6"
SEC_ID_ENSURE_SSH_MAXAUTHTRIES_LIMITED: "5.2.7"
SEC_ID_ENSURE_SSH_IGNORERHOSTS_ENABLED: "5.2.8"
SEC_ID_ENSURE_SSH_HOSTBASEDAUTHENTICATION_DISABLED: "5.2.9"
SEC_ID_ENSURE_SSH_ROOT_LOGIN_DISABLED: "5.2.10"
SEC_ID_ENSURE_SSH_EMPTY_PASSWORDS_DISABLED: "5.2.11"
SEC_ID_ENSURE_EMPTY_ENVIRONMENT_DISABLED: "5.2.12"
SEC_ID_ENSURE_STRONG_CIPHERS: "5.2.13"
SEC_ID_ENSURE_STRONG_MAC_ALGORITHMS: "5.2.14"
SEC_ID_ENSURE_STRONG_KEY_EXCHANGE_ALGORITHMS: "5.2.15"
SEC_ID_ENSURE_SSH_IDLE_TIMEOUT: "5.2.16"
SEC_ID_ENSURE_SSH_LOGINGRACETIME: "5.2.17"
SEC_ID_ENSURE_SSH_WARNING_BANNER: "5.2.18"
SEC_ID_ENSURE_SSH_PAM: "5.2.19"
SEC_ID_ENSURE_SSH_ALLOWTCPFORWARDING_DISABLED: "5.2.20"
SEC_ID_ENSURE_SSH_MAXSTARTUPS: "5.2.21"
SEC_ID_ENSURE_SSH_MAXSESSIONS_LIMITED: "5.2.22"


SEC_ID_CONFIGURE_PAM: "5.4"
SEC_ID_ENSURE_PASSWORD_CREATION_REQS: "5.4.1"
SEC_ID_ENSURE_FAILED_ATTEMPTS_LOCKOUT: "5.4.2"
SEC_ID_ENSURE_PASSWORD_HASH_SHA512: "5.4.3"
SEC_ID_ENSURE_PASSWORD_REUSE_LIMITED: "5.4.4"

SEC_ID_CONFIGURE_USER_ACCOUNTS_ENVIRONMENT: "5.5"
SEC_ID_ENSURE_PASSWORD_EXPIRY_365: "5.5.1.1"
SEC_ID_ENSURE_MINIMUM_DAYS_PASSWORD_CHANGE: "5.5.1.2"
SEC_ID_ENSURE_PASSWORD_EXPIRY_WARNING_7: "5.5.1.3"
SEC_ID_ENSURE_PASSWORD_LOCK_30: "5.5.1.4"
SEC_ID_ENSURE_PASSWORD_CHANGE_IN_PAST: "5.5.1.5"
SEC_ID_ENSURE_SYSTEM_ACCOUNTS_SECURED: "5.5.2"
SEC_ID_ENSURE_ROOT_DEFAULT_GROUP_0: "5.5.3"
SEC_ID_ENSURE_DEFAULT_USER_SHELL_TIMEOUT: "5.5.4"
SEC_ID_ENSURE_DEFAULT_USER_UMASK: "5.5.5"
SEC_ID_ENSURE_ROOT_LOGIN_CONSOLE: "5.6"
SEC_ID_ENSURE_SU_COMMAND_RESTRICTED: "5.7"


## Section 6 ##
SEC_ID_SYSTEM_FILE_PERMISSIONS: "6.1"
SEC_ID_AUDIT_SYSTEM_FILE_PERMISSIONS: "6.1.1"
SEC_ID_ENSURE_ETC_PASSWD_PERMISSIONS: "6.1.2"
SEC_ID_ENSURE_ETC_PASSWD_DASH_PERMISSIONS: "6.1.3"
SEC_ID_ENSURE_ETC_SHADOW_PERMISSIONS: "6.1.4"
SEC_ID_ENSURE_ETC_SHADOW_DASH_PERMISSIONS: "6.1.5"
SEC_ID_ENSURE_ETC_GSHADOW_DASH_PERMISSIONS: "6.1.6"
SEC_ID_ENSURE_ETC_GSHADOW_PERMISSIONS: "6.1.7"
SEC_ID_ENSURE_ETC_GROUP_PERMISSIONS: "6.1.8"
SEC_ID_ENSURE_ETC_GROUP_DASH_PERMISSIONS: "6.1.9"
SEC_ID_ENSURE_NO_WORLD_WRITABLE_FILES: "6.1.10"
SEC_ID_ENSURE_NO_UNOWNED_FILES_DIRS: "6.1.11"
SEC_ID_ENSURE_NO_UNGROUPED_FILES_DIRS: "6.1.12"
SEC_ID_AUDIT_SUID_EXECUTABLES: "6.1.13"
SEC_ID_AUDIT_SGID_EXECUTABLES: "6.1.14"

SEC_ID_USER_GROUP_SETTINGS: "6.2"
SEC_ID_ENSURE_ETC_PASSWD_USES_SHADOW: "6.2.1"
SEC_ID_ENSURE_ETC_SHADOW_NOT_EMPTY: "6.2.2"
SEC_ID_ENSURE_ETC_PASSWRD_EXIST_IN_ETC_GROUP: "6.2.3"
SEC_ID_ENSURE_SHADOW_GROUP_EMPTY: "6.2.4"
SEC_ID_ENSURE_NO_DUPLICATE_USERNAMES: "6.2.5"
SEC_ID_ENSURE_NO_DUPLICATE_GROUPNAMES: "6.2.6"
SEC_ID_ENSURE_NO_DUPLICATE_UIDS: "6.2.7"
SEC_ID_ENSURE_NO_DUPLICATE_GIDS: "6.2.8"
SEC_ID_ENSURE_ONLY_ROOT_UID_0: "6.2.9"
SEC_ID_ENSURE_ROOT_PATH_INTEGRITY: "6.2.10"
SEC_ID_ENSURE_ALL_HOMEDIRS_EXIST: "6.2.11"
SEC_ID_ENSURE_USERS_OWN_HOMEDIRS: "6.2.12"
SEC_ID_ENSURE_USERS_HOMEDIRS_PERMS: "6.2.13"
SEC_ID_ENSURE_USERS_DOTFILE_PERMS: "6.2.14"
SEC_ID_ENSURE_NO_DOTFORWARD: "6.2.15"
SEC_ID_ENSURE_NO_DOTNETRC: "6.2.16"
SEC_ID_ENSURE_NO_DOTRHOSTS: "6.2.17"
